import setuptools

setuptools.setup(
    name="teco-research",
    version="0.1.0",
    author="Pengyu Nie",
    author_email="prodigy.sov@gmail.com",
    description="Research on Test Completion",
    long_description="todo",
    url="https://github.com/pengyunie/teco",
    packages=setuptools.find_packages(include=["teco", "CodeBLEU"]),
    classifiers=[
        "Programming Language :: Python :: 3.8",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: POSIX :: Linux",
    ],
    install_requires=[
        "seutil>=0.8.2",
        "invoke~=2.0.0",
        "tqdm",
        "jsonargparse",
        "more-itertools~=8.6.0",
        "nltk~=3.6.7",
        "numpy~=1.22.2",
        "opt_einsum~=3.3.0",
        "fairscale~=0.4.13",
        "fuzzywuzzy[speedup]~=0.18.0",
        "deepspeed~=0.8.0",
        "pytorch-lightning==1.7.7",
        "rouge~=1.0.1",
        "scikit-learn~=1.1.1",
        "spdx-lookup~=0.3.3",
        "torch-tb-profiler~=0.3.1",
        "transformers~=4.25.1",
        "tree-sitter==0.19.0",
        "openai==0.26.5",
    ],
    extras_require={
        "dev": ["pytest", "flake8", "black", "ipykernel~=6.9.1"],
        "vis": [
            "seaborn~=0.11.2",
            "plotly~=5.6.0",
            "pytablewriter",
            "tabulate",
            "jsonnet",
        ],
        "dvc": ["dvc[azure]>=2.13.0", "azure-cli"],
        "toga": ["javalang==0.13.0"],
    },
)
